project_id = "fzkxeouvmkfvbtpzxeka"

[functions.crypto-search]
verify_jwt = false

[functions.crypto-analysis]
verify_jwt = false

[functions.crypto-news]
verify_jwt = false

[functions.trading-bot-ai]
verify_jwt = false