project_id = "fzkxeouvmkfvbtpzxeka"

# Only telegram-webhook needs to be public (receives calls from Telegram servers)
[functions.telegram-webhook]
verify_jwt = false

[functions.calendar-events]

[functions.learning-engine]

[functions.intraday-scanner]

[functions.intraday-scanner-vwap]

[functions.fundamental-analysis]

[functions.crypto-analysis]

[functions.crypto-news]

[functions.crypto-search]

[functions.market-analysis]

[functions.check-alerts]

[functions.send-telegram-alert]