project_id = "fzkxeouvmkfvbtpzxeka"

[functions.crypto-search]
verify_jwt = false

[functions.crypto-analysis]
verify_jwt = false

[functions.crypto-news]
verify_jwt = false

[functions.trading-bot-ai]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.send-telegram-alert]
verify_jwt = false

[functions.market-analysis]
verify_jwt = false

[functions.risk-calculator]
verify_jwt = false