project_id = "fzkxeouvmkfvbtpzxeka"

# Only telegram-webhook needs to be public (receives calls from Telegram servers)
[functions.telegram-webhook]
verify_jwt = false

[functions.calendar-events]

[functions.learning-engine]

[functions.intraday-scanner]

[functions.fundamental-analysis]